#!/usr/bin/env bash

export CLOUDFLARE_AUTH_KEY=${CLOUDFLARE_AUTH_KEY:-''}
export CLOUDFLARE_AUTH_EMAIL=${CLOUDFLARE_AUTH_EMAIL:-''}
export CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID:-''}
export CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID:-''}
export CLOUDFLARE_ZONE_NAME=${CLOUDFLARE_ZONE_NAME:-''}
